/* eslint-disable */
// Generated by Wrangler by running `wrangler types counter/worker-configuration.d.ts --config counter/wrangler.jsonc --include-runtime false` (hash: 2f8745dbb38782f5f482e35495f27bb0)
interface __BaseEnv_Env {
	DB: D1Database;
	SPIN_RATE_LIMITER: RateLimit;
	ALLOWED_ORIGIN: "https://vuducdung1308.github.io";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN">> {}
}
